name: Deploy VitePress site to GitHub Pages

on:
  push:
    branches:
      - main  


permissions:
  contents: write      # allows pushing to the repo
  pages: write         # allows configuring GitHub Pages
  id-token: write      # needed for secure deployments (recommended)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
        # Check-out repository
      - name: Checkout repository
        uses: actions/checkout@v3

        # Node.js environment setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Use latest version of Node.js

        #install dependancies
      - name: Install dependencies
        run: npm ci

        #Build the site page
      - name: Build VitePress site
        run: npm run build

        #deploy page on github pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist